<a href="https://colab.research.google.com/github/Kylalala13/PEMROGRAMAN/blob/main/KECERDASAN_BUATAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 1.	Tipe Data Python

In [ ]:
# Cek Tipe Data
print("\nCek Tipe Data")
var = 123
print(type(var))

# Tipe data String
print("\nTipe data String")
a = '123'
b = '3.4'
c = "Data String"
print(type(c))

# Tipe data numerik
print("\nTipe data numerik")
var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))
print(f1)
sum = var1 + var2
print(sum)
var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)
print(i2)

# Tipe Data Boolean
print("\nTipe Data Boolean")
print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

# Tipe Data List
print("\nTipe Data List")
list = ["belajar dasar python", 2023, 3.8, True]
print(list)
print(list[3])
print(list[1:3])
print(len(list))


Cek Tipe Data
<class 'int'>

Tipe data String
<class 'str'>

Tipe data numerik
<class 'float'>
345.0
379.5
34
12

Tipe Data Boolean
False
False
True
True

Tipe Data List
['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


2.	Operasi matematika menggunakan python

In [ ]:
# Operasi matematika menggunakan python
print("\nOperasi matematika menggunakan python")
x = min(5, 10, 25)
y = max(6, 12, 18)
print("Min:", x)
print("Max:", y)

# Mendapatkan nilai absolut
print("\nMendapatkan nilai absolut")
x_abs = abs(-7.25)
print("Absolut:", x_abs)

# Mendapatkan nilai pangkat
print("\nMendapatkan nilai pangkat")
x_pow = math.pow(4, 3)
print("Pangkat (4^3):", x_pow)

# Mendapatkan nilai akar
print("\nMendapatkan nilai akar")
x_sqrt = math.sqrt(64)
print("Akar (sqrt 64):", x_sqrt)

# Mendapatkan nilai pembulatan
print("\nMendapatkan nilai pembulatan")
x_ceil = math.ceil(1.4)
y_floor = math.floor(1.4)
print("Pembulatan ke atas (ceil):", x_ceil)
print("Pembulatan ke bawah (floor):", y_floor)

# Mendapatkan nilai konstanta (PI)
print("\nMendapatkan nilai konstanta (PI)")
x_pi = math.pi
print("Nilai PI:", x_pi)


Operasi matematika menggunakan python
Min: 5
Max: 18

Mendapatkan nilai absolut
Absolut: 7.25

Mendapatkan nilai pangkat
Pangkat (4^3): 64.0

Mendapatkan nilai akar
Akar (sqrt 64): 8.0

Mendapatkan nilai pembulatan
Pembulatan ke atas (ceil): 2
Pembulatan ke bawah (floor): 1

Mendapatkan nilai konstanta (PI)
Nilai PI: 3.141592653589793


3.	Menggunakan Fungsi MATH

In [ ]:
import math

# 1. math.sin() -> Menghitung sinus (dalam radian)
print("\nMath sin")
print("Sinus 90 derajat:", math.sin(math.radians(90)))

# 2. math.cos() -> Menghitung cosinus (dalam radian)
print("\nmath.cos")
print("Cosinus 0 derajat:", math.cos(math.radians(0)))

# 3. math.tan() -> Menghitung tangen (dalam radian)
print("\nmath.tan")
print("Tangen 45 derajat:", math.tan(math.radians(45)))

# 4. math.log() -> Logaritma natural (basis e)
print("\nmath.log")
print("Logaritma natural dari 10:", math.log(10))

# 5. math.log10() -> Logaritma basis 10
print("\nmath.log10")
print("Logaritma basis 10 dari 100:", math.log10(100))

# 6. math.degrees() -> Mengubah radian ke derajat
print("\nmath.degrees")
print("Radian (pi) ke Derajat:", math.degrees(math.pi))

# 7. math.dist() -> Menghitung jarak Euclidean antara dua titik [x,y]
print("\nmath.dist")
titik1 = [0, 0]
titik2 = [3, 4]
print("Jarak antara titik (0,0) dan (3,4):", math.dist(titik1, titik2))

# 8. math.factorial() -> Menghitung faktorial
print("\nmath.factorial")
print("Faktorial dari 5 (5!):", math.factorial(5))

# 9. math.fmod() -> Menghitung sisa bagi (modulus) angka desimal
print("\nmath.fmod")
print("Sisa bagi 10.5 dengan 3:", math.fmod(10.5, 3))

# 10. math.isnan() -> Mengecek apakah nilai tersebut 'Not a Number' (NaN)
print("\nmath.isnan")
print("Apakah 'NaN' itu NaN?:", math.isnan(float('nan')))

# 11. math.gamma() -> Menghitung fungsi Gamma
print("\nmath.gamma")
print("Fungsi Gamma dari 6:", math.gamma(6))

# 12. math.perm() -> Menghitung permutasi (nPk)
# Contoh: 5P2 (Permutasi 2 dari 5 objek)
print("\nmath.perm")
print("Permutasi 5P2:", math.perm(5, 2))


Math sin
Sinus 90 derajat: 1.0

math.cos
Cosinus 0 derajat: 1.0

math.tan
Tangen 45 derajat: 0.9999999999999999

math.log
Logaritma natural dari 10: 2.302585092994046

math.log10
Logaritma basis 10 dari 100: 2.0

math.degrees
Radian (pi) ke Derajat: 180.0

math.dist
Jarak antara titik (0,0) dan (3,4): 5.0

math.factorial
Faktorial dari 5 (5!): 120

math.fmod
Sisa bagi 10.5 dengan 3: 1.5

math.isnan
Apakah 'NaN' itu NaN?: True

math.gamma
Fungsi Gamma dari 6: 120.0

math.perm
Permutasi 5P2: 20



4.	Operasi matriks dan vektor dengan python


In [ ]:
# Membuat matriks di pyhon
print("\nMembuat matriks di python")
import numpy as np
# --- Penjumlahan Matriks ---
A = np.array([[80, 30, 25], [50, 20, 10]])
B = np.array([[30, 60, 15], [10, 30, 30]])
hasil_tambah = A + B
print("Hasil Penjumlahan Matriks:")
print(hasil_tambah)
print("-" * 30)

# --- Operasi Dot Product (Perkalian Titik) ---
print("\nOperasi Dot Product (Perkalian Titik)")
# Menghasilkan satu nilai skalar
A_vec = np.array([10, 20, 15])
B_vec = np.array([16, 67, 35])
hasil_dot = np.dot(A_vec, B_vec)
print("Hasil Dot Product:", hasil_dot)
print("-" * 30)

# --- Operasi Cross Product (Perkalian Silang) ---
print("\nOperasi Cross Product (Perkalian Silang)")
# Menghasilkan vektor baru yang tegak lurus
Hasil_cross = np.cross(A_vec, B_vec)
print("Hasil Cross Product:", Hasil_cross)


Membuat matriks di python
Hasil Penjumlahan Matriks:
[[110  90  40]
 [ 60  50  40]]
------------------------------

Operasi Dot Product (Perkalian Titik)
Hasil Dot Product: 2025
------------------------------

Operasi Cross Product (Perkalian Silang)
Hasil Cross Product: [-305 -110  350]


PRAKTIKUM NO 1

In [ ]:
# --- No. 1: Operasi Matriks ---
# Definisi matriks sesuai soal [cite: 186]
A_mat = np.array([[3, 1], [2, 0]])
B_mat = np.array([[2, 1], [1, -1]])
C_mat = np.array([[-1, 1, 2], [2, 0, -1]])

# Tentukan A x B [cite: 188]
hasil_AxB = np.matmul(A_mat, B_mat)
print("Hasil A x B:\n", hasil_AxB)

# Tentukan B . C [cite: 189]
hasil_BC = np.matmul(B_mat, C_mat)
print("\nHasil B . C:\n", hasil_BC)

Hasil A x B:
 [[7 2]
 [4 2]]

Hasil B . C:
 [[ 0  2  3]
 [-3  1  3]]


PRAKTIKUM NO 2

In [ ]:
# --- No. 2: Faktorial ---
# Hitung 6! [cite: 191]
faktorial_6 = math.factorial(6)
print(f"\nHail 6! {faktorial_6}")

# Hitung 8! / 5! [cite: 192]
faktorial_8_5 = math.factorial(8) / math.factorial(5)
print(f"Hasil 8! / 5!: {faktorial_8_5}")


Hail 6! 720
Hasil 8! / 5!: 336.0


PRAKTIKUM NO 3

In [ ]:
# --- No. 3: Operasi Vektor 3D ---
# Vektor A = 5i + 3j + 7k dan B = 12i – 3j + k [cite: 194]
vec_A = np.array([5, 3, 7])
vec_B = np.array([12, -3, 1])

# Panjang masing-masing Vektor [cite: 195]
panjang_A = np.linalg.norm(vec_A)
panjang_B = np.linalg.norm(vec_B)
print(f"\nPanjang Vektor A: {panjang_A}")
print(f"Panjang Vektor B: {panjang_B}")

# Hasil perkalian titik A.B [cite: 195]
titik_AB = np.dot(vec_A, vec_B)
print(f"Hasil A.B (Dot Product): {titik_AB}")

# Hasil perkalian silang AxB [cite: 195]
silang_AB = np.cross(vec_A, vec_B)
print(f"Hasil AxB (Cross Product): {silang_AB}")


Panjang Vektor A: 9.1104335791443
Panjang Vektor B: 12.409673645990857
Hasil A.B (Dot Product): 58
Hasil AxB (Cross Product): [ 24  79 -51]
